CREATE TABLE IF NOT EXISTS `user`(
    id INT AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,

    PRIMARY KEY(id)
)